-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS AbstractArticle CASCADE;
DROP TABLE IF EXISTS Language CASCADE;
DROP TABLE IF EXISTS Article CASCADE;
DROP TABLE IF EXISTS ArticleVersion CASCADE;
DROP TABLE IF EXISTS ArticleSuperclass CASCADE;
DROP TABLE IF EXISTS Message CASCADE;
DROP TABLE IF EXISTS Person CASCADE;



